epoch: 20
loss: nn.BCEWithLogitsLoss
model:
  name: swin_tiny_patch4_window7_224
  output_dim: 1
n_splits: 5
optimizer:
  name: optim.AdamW
  params:
    lr: 1.0e-05
root: /home/olga/Programs/mlops-hw/data
scheduler:
  name: optim.lr_scheduler.CosineAnnealingWarmRestarts
  params:
    T_0: 20
    eta_min: 0.0001
seed: 2021
train_loader:
  batch_size: 64
  drop_last: true
  num_workers: 4
  pin_memory: false
  shuffle: true
trainer:
  accumulate_grad_batches: 1
  fast_dev_run: false
  num_sanity_val_steps: 0
transform:
  image_size: 224
  name: get_default_transforms
val_loader:
  batch_size: 64
  drop_last: false
  num_workers: 4
  pin_memory: false
  shuffle: false
output: solution.csv
test: test.csv
test_dir: test
train: train.csv
train_dir: train
best_ckpt: default/version_0/checkpoints/best_loss.ckpt
