affine:
  degrees: 15
  translate: [0.1, 0.1]
  scale: [0.9, 1.1]
color_jitter:
  brightness: 0.1
  contrast: 0.1
  saturation: 0.1
imagenet_mean: [0.485, 0.456, 0.406]
imagenet_std: [0.229, 0.224, 0.225]
